name: "Build and Test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - name: "Setup Rust"
        uses: "actions-rust-lang/setup-rust-toolchain@v1"
      - run: "cargo fmt --check"
      - run: "cargo build"
      - run: "cargo test"
